name: Publish Python Package to GitHub Packages

on:
  push:
    branches:
      - main  # Trigger this action when pushing to the main branch
  workflow_dispatch:  # Allow manually triggering the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the Python version your package requires

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package to Azure Artifacts
        env:
          TWINE_USERNAME: __token__  # Azure requires "__token__" for authentication via PAT
          TWINE_PASSWORD: ${{ secrets.AZURE_ARTIFACTS_PAT }}  # Your Azure PAT stored in GitHub secrets
        run: |
          python -m twine upload --repository-url ${{ secrets.AZURE_FEED_URL }} dist/*

      - name: Clean up build artifacts
        run: |
          rm -rf dist build *.egg-info